### ISSUE TITLE
Profile Calculator Downloads Empty .osu File

### ISSUE THREAD

**Issue by VINXIS** [ppy/osu-tools#18]
I ran the profile command on [Mismagius's profile](https://osu.ppy.sh/u/mismagius), and I ran into an error after 1 of the maps downloaded. The last map that was downloaded was [this](https://osu.ppy.sh/b/279481?m=0) map which seems to be an empty .osu file Upon Inspection:
![Empty](https://imbouttaheadout.s-ul.eu/yA2kB5A5)

The error that was given was this as a result:
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: Unknown file format (null)
   at osu.Game.Beatmaps.Formats.Decoder.GetDecoder[T](StreamReader stream) in A:\Users\oykxf\Documents\osu-tools\osu\osu.Game\Beatmaps\Formats\Decoder.cs:line 60
   at PerformanceCalculator.ProcessorWorkingBeatmap.readFromFile(String filename) in A:\Users\oykxf\Documents\osu-tools\PerformanceCalculator\ProcessorWorkingBeatmap.cs:line 44
   at PerformanceCalculator.ProcessorWorkingBeatmap..ctor(String file, Nullable`1 beatmapId) in A:\Users\oykxf\Documents\osu-tools\PerformanceCalculator\ProcessorWorkingBeatmap.cs:line 25
   at PerformanceCalculator.Profile.ProfileCommand.Execute() in A:\Users\oykxf\Documents\osu-tools\PerformanceCalculator\Profile\ProfileCommand.cs:line 63
   at PerformanceCalculator.ProcessorCommand.OnExecute(CommandLineApplication app, IConsole console) in A:\Users\oykxf\Documents\osu-tools\PerformanceCalculator\ProcessorCommand.cs:line 26
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments) in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 86
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<OnExecute>d__1.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext() in C:\projects\commandlineutils\src\CommandLineUtils\Conventions\ExecuteMethodConvention.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass126_0.<OnExecute>b__0() in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 505
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.Execute.cs:line 31
   at PerformanceCalculator.Program.Main(String[] args) in A:\Users\oykxf\Documents\osu-tools\PerformanceCalculator\Program.cs:line 27
```

**Comment by qwewqa** [comment]
It's https://osu.ppy.sh/beatmapsets/106443#osu/279481 I believe

**Comment by VINXIS** [comment]
woops fixed

**Comment by qwewqa** [comment]
Seems like https://osu.ppy.sh/osu/279481 just isn't returning anything

**Comment by TheRamsay** [comment]
This map https://osu.ppy.sh/beatmapsets/330671#osu/732724

**Comment by TheRamsay** [comment]
I was calcing JeDDy´s profile and this map brought the same issue https://osu.ppy.sh/beatmapsets/330671#osu/732724

**Comment by omkelderman** [comment]
https://github.com/ppy/osu-api/issues/171

**Comment by TheRamsay** [comment]
> [ppy/osu-api#171](https://github.com/ppy/osu-api/issues/171)

Thats the solution for it? I dont understand what should I do.

**Comment by omkelderman** [comment]
sorry, should have left a comment with it, thought it would explain itself. Basically thats a place where the exact same problem has been logged about 2 years ago, with unfortunately no solution yet.

So all we can do is hope it gets fixed and monitor that issue there

**Comment by TheRamsay** [comment]
Ok, thx. I hope VINXIS will fix it soon. BlessRNG

**Comment by omkelderman** [comment]
this is a problem on peppy's server, only he can solve this

**Comment by TheRamsay** [comment]
So why Vinxis said "woops fixed"? He cant fix it by himself?

**Comment by qwewqa** [comment]
He meant the link

**Comment by TheRamsay** [comment]
Oh I am retarded lulw. Thx

**Comment by peppy** [comment]
All of these have been fixed.
